# Final position
px:  -2.85   
py:   0.0000 
pz:   4.25   

# Final orientation
qw:   0.0001
qx:   0.7071
qy:   0.0001
qz:   0.7071


# Final linear and angular velocities (typically 0)
vx: 0.0
vy: 0.0
vz: 0.0
wx: 0.0
wy: 0.0
wz: 0.0