px: 1.0   
py: 0.01  
pz: 4.20  
qw: 0.7071
qx: -0.001
qy: -0.001
qz: 0.7071

# Initial linear and angular velocities (typically 0)
vx: 0.0
vy: 0.0
vz: 0.0
wx: 0.0
wy: 0.0
wz: 0.0

# Initial thrusts (not used by default)
t0: 0
t1: 0
t2: 0
t3: 0