px: 1.0   #1.0
py: 0.01  #0.0
pz: 4.20  #1.5
qw: 0.0   # 0.0 # 0.713 #1.0
qx: 0.0   # 0.0 # 0.0
qy: 0.0   # 0.0 # 0.0
qz: 1.0   # 1.0 # 0.701 #0.0

# Initial linear and angular velocities (typically 0)
vx: 0.0
vy: 0.0
vz: 0.0
wx: 0.0
wy: 0.0
wz: 0.0

# Initial thrusts (not used by default)
t0: 0
t1: 0
t2: 0
t3: 0